package org.hytaledevlib.tools;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Tool to generate a hardcoded BlockIds class from mapping.txt.
 * Run this tool to regenerate BlockIds.java whenever block mappings change.
 */
public class BlockMappingGenerator {
    
    public static void main(String[] args) {
        String inputFile = "src/main/java/org/grounditems/mapping.txt";
        String outputFile = "src/main/java/org/grounditems/lib/BlockIds.java";
        
        try {
            generateBlockIdsClass(inputFile, outputFile);
            System.out.println("Successfully generated " + outputFile);
            System.out.println("Total blocks mapped: " + countBlocks(inputFile));
        } catch (IOException e) {
            System.err.println("Error generating BlockIds class: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private static void generateBlockIdsClass(String inputFile, String outputFile) throws IOException {
        List<BlockMapping> mappings = parseMapping(inputFile);
        
        StringBuilder sb = new StringBuilder();
        sb.append("package org.hytaledevlib.lib;\n\n");
        sb.append("import java.util.HashMap;\n");
        sb.append("import java.util.Map;\n\n");
        sb.append("/**\n");
        sb.append(" * Hardcoded block ID to name mappings for Hytale.\n");
        sb.append(" * Generated by BlockMappingGenerator tool.\n");
        sb.append(" * Total blocks: ").append(mappings.size()).append("\n");
        sb.append(" * \n");
        sb.append(" * DO NOT EDIT THIS FILE MANUALLY!\n");
        sb.append(" * Regenerate using: BlockMappingGenerator.main()\n");
        sb.append(" */\n");
        sb.append("public class BlockIds {\n\n");
        
        // Generate constants for each block
        sb.append("    // Block ID constants\n");
        for (BlockMapping mapping : mappings) {
            String constantName = mapping.name.toUpperCase().replace("-", "_").replace("*", "");
            sb.append("    public static final int ").append(constantName)
              .append(" = ").append(mapping.id).append(";\n");
        }
        
        sb.append("\n    // Name to ID mapping\n");
        sb.append("    private static final Map<String, Integer> NAME_TO_ID = new HashMap<>();\n");
        sb.append("    private static final Map<Integer, String> ID_TO_NAME = new HashMap<>();\n\n");
        
        // Split initialization into multiple methods to avoid 65535 byte limit
        sb.append("    static {\n");
        sb.append("        init0();\n");
        sb.append("        init1();\n");
        sb.append("        init2();\n");
        sb.append("        init3();\n");
        sb.append("        init4();\n");
        sb.append("        init5();\n");
        sb.append("        init6();\n");
        sb.append("        init7();\n");
        sb.append("    }\n\n");
        
        // Split mappings into 8 methods (roughly 500 blocks each)
        int methodCount = 8;
        int blocksPerMethod = (mappings.size() + methodCount - 1) / methodCount;
        
        for (int methodIndex = 0; methodIndex < methodCount; methodIndex++) {
            sb.append("    private static void init").append(methodIndex).append("() {\n");
            
            int startIdx = methodIndex * blocksPerMethod;
            int endIdx = Math.min(startIdx + blocksPerMethod, mappings.size());
            
            for (int i = startIdx; i < endIdx; i++) {
                BlockMapping mapping = mappings.get(i);
                sb.append("        NAME_TO_ID.put(\"").append(mapping.name).append("\", ").append(mapping.id).append(");\n");
                sb.append("        ID_TO_NAME.put(").append(mapping.id).append(", \"").append(mapping.name).append("\");\n");
            }
            
            sb.append("    }\n\n");
        }
        
        // Add utility methods
        sb.append("    /**\n");
        sb.append("     * Get block ID by name.\n");
        sb.append("     * @param name Block name\n");
        sb.append("     * @return Block ID, or -1 if not found\n");
        sb.append("     */\n");
        sb.append("    public static int getId(String name) {\n");
        sb.append("        Integer id = NAME_TO_ID.get(name);\n");
        sb.append("        return id != null ? id : -1;\n");
        sb.append("    }\n\n");
        
        sb.append("    /**\n");
        sb.append("     * Get block name by ID.\n");
        sb.append("     * @param id Block ID\n");
        sb.append("     * @return Block name, or null if not found\n");
        sb.append("     */\n");
        sb.append("    public static String getName(int id) {\n");
        sb.append("        return ID_TO_NAME.get(id);\n");
        sb.append("    }\n\n");
        
        sb.append("    /**\n");
        sb.append("     * Check if block name exists.\n");
        sb.append("     * @param name Block name\n");
        sb.append("     * @return true if exists\n");
        sb.append("     */\n");
        sb.append("    public static boolean hasBlock(String name) {\n");
        sb.append("        return NAME_TO_ID.containsKey(name);\n");
        sb.append("    }\n\n");
        
        sb.append("    /**\n");
        sb.append("     * Check if block ID exists.\n");
        sb.append("     * @param id Block ID\n");
        sb.append("     * @return true if exists\n");
        sb.append("     */\n");
        sb.append("    public static boolean hasBlock(int id) {\n");
        sb.append("        return ID_TO_NAME.containsKey(id);\n");
        sb.append("    }\n\n");
        
        sb.append("    /**\n");
        sb.append("     * Get all block mappings.\n");
        sb.append("     * @return Map of name to ID\n");
        sb.append("     */\n");
        sb.append("    public static Map<String, Integer> getAllBlocks() {\n");
        sb.append("        return new HashMap<>(NAME_TO_ID);\n");
        sb.append("    }\n\n");
        
        sb.append("    /**\n");
        sb.append("     * Get total block count.\n");
        sb.append("     * @return Number of blocks\n");
        sb.append("     */\n");
        sb.append("    public static int getBlockCount() {\n");
        sb.append("        return NAME_TO_ID.size();\n");
        sb.append("    }\n");
        
        sb.append("}\n");
        
        // Write to file
        try (FileWriter writer = new FileWriter(outputFile)) {
            writer.write(sb.toString());
        }
    }
    
    private static List<BlockMapping> parseMapping(String inputFile) throws IOException {
        List<BlockMapping> mappings = new ArrayList<>();
        
        try (BufferedReader reader = new BufferedReader(new FileReader(inputFile))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.contains("Block ID ")) {
                    try {
                        int idStart = line.indexOf("Block ID ") + 9;
                        int idEnd = line.indexOf(":", idStart);
                        int id = Integer.parseInt(line.substring(idStart, idEnd).trim());
                        String name = line.substring(idEnd + 1).trim();
                        
                        mappings.add(new BlockMapping(id, name));
                    } catch (Exception e) {
                        System.err.println("Failed to parse line: " + line);
                    }
                }
            }
        }
        
        return mappings;
    }
    
    private static int countBlocks(String inputFile) throws IOException {
        int count = 0;
        try (BufferedReader reader = new BufferedReader(new FileReader(inputFile))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.contains("Block ID ")) {
                    count++;
                }
            }
        }
        return count;
    }
    
    private static class BlockMapping {
        int id;
        String name;
        
        BlockMapping(int id, String name) {
            this.id = id;
            this.name = name;
        }
    }
}
